parkinsons.csv <- read.csv("C:/Parkinsons Classification/parkinsons.csv.data")
View(parkinsons.csv)
myData = parkinsons.csv
View(myData)
myData = myData[,-1]
myData$status=as.factor((myData$status))
myData = parkinsons.csv
summary(myData)
myData = parkinsons.csv
View(myData)
summary(myData)
myData = myData[,-1]
summary(myData)
myData$status=as.factor((myData$status))
summary(myData)
dim(myData)
Parkinsons_model=glm(status~., data = myData, family = binomial)
summary(Parkinsons_model)
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz. , data = myData, family = binomial)
Parkinsons_model_1=glm(status~. MDVP.Jitter...+MDVP.PPQ+MDVP.Shimmer.dB. +RPDE +DFA +spread2 +D2+PPE  , data = myData, family = binomial)
Parkinsons_model_1=glm(status~. MDVP.Jitter...+MDVP.PPQ+MDVP.Shimmer.dB.+RPDE+DFA+spread2+D2+PPE, data = myData, family = binomial)
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz. -MDVP.Jitter.Abs., data = myData, family = binomial)
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz. -MDVP.Jitter.Abs. -MDVP.RAP -Jitter.DDP -MDVP.Shimmer, data = myData, family = binomial)
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz. -MDVP.Jitter.Abs. -MDVP.RAP -Jitter.DDP -MDVP.Shimmer -Shimmer.APQ3 -Shimmer.DDA -NHR -HNR -spread1 , data = myData, family = binomial)
View((Parkinsons_model_1))
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz. -MDVP.Jitter.Abs. -MDVP.RAP -Jitter.DDP -MDVP.Shimmer -Shimmer.APQ3 -Shimmer.DDA -NHR -HNR -spread1 , data = myData, family = binomial)
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz. -MDVP.Jitter.Abs. -MDVP.RAP -Jitter.DDP -MDVP.Shimmer -Shimmer.APQ3 -Shimmer.DDA -NHR -HNR -spread1 , data = myData, family = binomial)
View((Parkinsons_model_1))
library(boot)
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz. -MDVP.Jitter.Abs. -MDVP.RAP -Jitter.DDP -MDVP.Shimmer -Shimmer.APQ3 -Shimmer.DDA -NHR -HNR -spread1 , data = myData, family = binomial)
View((Parkinsons_model_1))
Parkinsons_model_1=glm(status~ spread2+MDVP.Jitter..., data = myData, family = binomial)
View(Parkinsons_model_1)
Parkinsons_model=glm(status~., data = myData, family = binomial)
summary(Parkinsons_model)
MDVP.Jitter.Abs. -MDVP.RAP -Jitter.DDP -MDVP.Shimmer -Shimmer.APQ3 -Shimmer.DDA -NHR -HNR -spread1
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz., data = myData, family = binomial)
View(Parkinsons_model_1)
Parkinsons_model_1=glm(status~. spread2, data = myData, family = binomial)
Parkinsons_model_1=glm(status~ spread2, data = myData, family = binomial)
View(Parkinsons_model_1)
library(boot)
Parkinsons_model_1=glm(status~ spread2, data = myData, family = binomial)
View(Parkinsons_model_1)
parkinsons.data <- read.csv("C:/Parkinsons Classification/parkinsons.data.data")
View(parkinsons.data)
myData = parkinsons.data
View(myData)
myData = myData[,-1]
myData$status=as.factor((myData$status))
summary(myData)
dim(myData)
library(boot)
Parkinsons_model=glm(status~., data = myData, family = binomial)
summary(Parkinsons_model)
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz. -MDVP.Jitter.Abs. -MDVP.RAP -Jitter.DDP -MDVP.Shimmer -Shimmer.APQ3 -Shimmer.DDA -NHR -HNR -spread1 , data = myData, family = binomial)
View((Parkinsons_model_1))
myData = cbind(parkinsons.data[,"MDVP.PPQ"],parkinsons.data[,"DFA"],parkinsons.data[,"status"],parkinsons.data[,"spread2"])
View(myData)
myData = cbind(parkinsons.data[,"MDVP.Jitter..."],parkinsons.data[,"MDVP.PPQ"],parkinsons.data[,"DFA"],parkinsons.data[,"spread2"],parkinsons.data[,"D2"],parkinsons.data[,"PPE"],parkinsons.data[,"status"])
View(myData)
summary(myData)
colnames(myData)=c("MDVP.Jitter...", "MDVP.PPQ","DFA","spread2", "D2","PPE","status")
View(myData)
summary(myData)
Parkinsons_model_1=glm(status~., data = myData, family = binomial)
Parkinsons_model=glm(status~., data = myData, family = binomial)
library(boot)
Parkinsons_model=glm(status~., data = myData, family = binomial)
myData_1 = cbind(parkinsons.data[,"MDVP.Jitter..."],parkinsons.data[,"MDVP.PPQ"],parkinsons.data[,"DFA"],parkinsons.data[,"spread2"],parkinsons.data[,"D2"],parkinsons.data[,"PPE"],parkinsons.data[,"status"])
myData_1 = cbind(parkinsons.data[,"MDVP.Jitter..."],parkinsons.data[,"MDVP.PPQ"],parkinsons.data[,"DFA"],parkinsons.data[,"spread2"],parkinsons.data[,"D2"],parkinsons.data[,"PPE"],parkinsons.data[,"status"])
View(myData_1)
summary(myData_1)
colnames(myData_1)=c("MDVP.Jitter...", "MDVP.PPQ","DFA","spread2", "D2","PPE","status")
View(myData_1)
summary(myData_1)
library(boot)
Parkinsons_model=glm(status~., data = myData_1, family = binomial)
myDataClean = as.data.frame(myData_1)
library(boot)
Parkinsons_model=glm(status~., data = myDataClean, family = binomial)
summary(Parkinsons_model)
train = sample(195,135)
Parkinsons_model_2=glm(start~., data=myDataClean, subset=train, family=binomial)
train = sample(195,135)
Parkinsons_model_2=glm(status~., data=myDataClean, subset=train, family=binomial)
summary(Parkinsons_model_2)
Parkinsons_model_2.probs=predict(Parkinsons_model_2, myDataClean[-train,], type="response")
Parkinsons_model_2.pred = rep(0,60)
Parkinsons_model_2.pred[Parkinsons_model_2.probs > .5] = 1
table(myDataClean[-train,]$status, Parkinsons_model_2.pred)
library(MASS)
Parkinsons_model_lda = lda(status~., data = myDataClean)
summary(Parkinsons_model_lda)
Parkinsons_model_lda
train = sample(195,135)
Parkinsons_model_lda_1 = lda(status~., data=myDataClean, subset=train)
Parkinsons_model_lda_1.pred = predict(Parkinsons_model_lda_1,myDataClean[-train,])
names(Parkinsons_model_lda_1.pred)
Parkinsons_model_lda_1.class = Parkinsons_model_lda_1.pred$class
table(Parkinsons_model_lda_1.class,myDataClean[-train,7])
mean(Parkinsons_model_lda_1.class == myDataClean[-train,7])
savehistory("~/Desktop/Project/Project_4_b.R")
