fieldgoal_data <- read.csv("C:/fieldgoal_data.dat", sep="")
View(fieldgoal_data)
colnames(fieldgoal_data)=c("Distance", "Success_indicator","Week")
myData = fieldgoal_data
View(myData)
myData$Success_indicator=as.factor((myData$Success_indicator))
myData$Week=as.factor((myData$Week))
summary(myData)
dim(myData)
NFL_model_1=glm(Success_indicator~., data = myData, family = binomial)
summary((NFL_model_1))
plot(myData)
library(boot)
train = sample(947,700)
NFL_model_2=glm(Success_indicator~., data=myData, subset=train, family=binomial)
summary(NFL_model_2)
NFL_model_2.probs=predict(NFL_model_2, myData[-train,], type="response")
NFL_model_2.pred = rep(0,247)
NFL_model_2.pred[NFL_model_2.probs > .5] = 1
table(myData[-train,]$Success_indicator, NFL_model_2.pred)
#delete week, have a try
NFL_model_3=glm(Success_indicator~. -Week, data = myData, subset=train, family=binomial)
summary(NFL_model_3)
NFL_model_3.probs=predict(NFL_model_3, myData[-train,], type="response")
NFL_model_3.pred = rep(0,247)
NFL_model_3.pred[NFL_model_3.probs > .5] = 1
table(myData[-train,]$Success_indicator, NFL_model_3.pred)
NFL_model_3.pred = rep(0,247)
NFL_model_3.pred[NFL_model_3.probs > .7] = 1
table(myData[-train,]$Success_indicator, NFL_model_3.pred)
library(MASS)
NFL_model_lda = lda(Success_indicator~., data = myData)
summary(NFL_model_lda)
NFL_model_lda
train = sample(947,700)
NFL_model_lda_1 = lda(Success_indicator~., data=myData, subset=train)
NFL_model_lda_1.pred = predict(NFL_model_lda_1,myData[-train,])
names(NFL_model_lda_1.pred)
NFL_model.class = NFL_model_lda_1.pred$class
table(NFL_model.class,myData[-train,2])
mean(NFL_model.class == myData[-train,2])
NFL_model_qda = qda(Success_indicator~., data = myData)
summary(NFL_model_qda)
NFL_model_qda
train = sample(947,700)
NFL_model_qda_1 = qda(Success_indicator~., data=myData, subset=train)
NFL_model_qda_1.pred = predict(NFL_model_qda_1,myData[-train,])
names(NFL_model_qda_1.pred)
NFL_model.class = NFL_model_qda_1.pred$class
table(NFL_model.class,myData[-train,2])
mean(NFL_model.class == myData[-train,2])
parkinsons.data <- read.csv("C:/parkinsons.data.data")
View(parkinsons.data)
parkinsons.csv <- read.csv("C://parkinsons.csv.data")
View(parkinsons.csv)
myData = parkinsons.csv
View(myData)
summary(myData)
myData = myData[,-1]
summary(myData)
myData$status=as.factor((myData$status))
summary(myData)
dim(myData)
Parkinsons_model=glm(status~., data = myData, family = binomial)
summary(Parkinsons_model)
dim(myData)
Parkinsons_model=glm(status~., data = myData, family = binomial)
summary(Parkinsons_model)
plot(myData)
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz , data = myData, family = binomial)
attach(myData)
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz, data = myData, family=binomial)
library(boot)
attach(myData)
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz, data = myData, family=binomial)
myData_1= cbind(parkinsons.csv[,"MDVP.Jitter..."],titanic[,"MDVP.PPQ "],titanic[,"spread2 "],titanic[,"PPE"])
myData_1= cbind(parkinsons.csv[,"MDVP.Jitter..."],parkinsons.csv[,"MDVP.PPQ "],parkinsons.csv[,"spread2 "],parkinsons.csv[,"PPE"])
myData_1= cbind(myData[,"MDVP.Jitter..."],myData[,"MDVP.PPQ "],myData[,"spread2 "],myData[,"PPE"])
attach(myData)
myData_1= cbind(myData[,"MDVP.Jitter..."],myData[,"MDVP.PPQ "],myData[,"spread2 "],myData[,"PPE"])
Parkinsons_model_1=glm(status~. -MDVP.Flo.Hz., data = myData, family = binomial)
View(Parkinsons_model_1)
savehistory("~/Desktop/Project/Project_4_a.R")
