View(student.mat)
sink("output_mat.txt")
myData_mat = student.mat
dim(myData_mat)
summary(myData_mat)
##set following variables as factor variables
myData_mat[,3]=as.ordered(myData_mat[,3])
myData_mat[,7]=as.ordered(myData_mat[,7])
myData_mat[,8]=as.ordered(myData_mat[,8])
myData_mat[,13]=as.ordered(myData_mat[,13])
myData_mat[,14]=as.ordered(myData_mat[,14])
myData_mat[,15]=as.ordered(myData_mat[,15])
myData_mat[,24]=as.ordered(myData_mat[,24])
myData_mat[,25]=as.ordered(myData_mat[,25])
myData_mat[,26]=as.ordered(myData_mat[,26])
myData_mat[,27]=as.ordered(myData_mat[,27])
myData_mat[,28]=as.ordered(myData_mat[,28])
myData_mat[,29]=as.ordered(myData_mat[,29])
myData_mat[,30]=as.ordered(myData_mat[,30])
myData_mat[,31]=as.ordered(myData_mat[,31])
myData_mat[,32]=as.ordered(myData_mat[,32])
myData_mat[,33]=as.ordered(myData_mat[,33])
summary(myData_mat)
##myData_mat = as.data.frame(myData_mat)
library("arules")
##library("arules", lib.loc="~/R/win-library/3.2")
##rules = apriori(myData_mat)
rules <- apriori(myData_mat, parameter = list(minlen=2, supp=0.008, conf=0.8), appearance = list(rhs=c("Dalc=5"),default = "lhs"))
##inspect(rules)
rules.sorted = sort(rules, by="lift")
inspect(rules.sorted)
myData_mat = student.mat
dim(myData_mat)
summary(myData_mat)
##set following variables as factor variables
myData_mat[,3]=as.ordered(myData_mat[,3])
myData_mat[,7]=as.ordered(myData_mat[,7])
myData_mat[,8]=as.ordered(myData_mat[,8])
myData_mat[,13]=as.ordered(myData_mat[,13])
myData_mat[,14]=as.ordered(myData_mat[,14])
myData_mat[,15]=as.ordered(myData_mat[,15])
myData_mat[,24]=as.ordered(myData_mat[,24])
myData_mat[,25]=as.ordered(myData_mat[,25])
myData_mat[,26]=as.ordered(myData_mat[,26])
myData_mat[,27]=as.ordered(myData_mat[,27])
myData_mat[,28]=as.ordered(myData_mat[,28])
myData_mat[,29]=as.ordered(myData_mat[,29])
myData_mat[,30]=as.ordered(myData_mat[,30])
myData_mat[,31]=as.ordered(myData_mat[,31])
myData_mat[,32]=as.ordered(myData_mat[,32])
myData_mat[,33]=as.ordered(myData_mat[,33])
## show summary after changing numerical to factor variables
summary(myData_mat)
##myData_mat = as.data.frame(myData_mat)
sink("output_mat.txt")
library("arules")
##library("arules", lib.loc="~/R/win-library/3.2")
##rules = apriori(myData_mat)
rules <- apriori(myData_mat, parameter = list(minlen=2, supp=0.007, conf=0.8), appearance = list(rhs=c("Dalc=5", "Walc=5"),default = "lhs"))
##inspect(rules)
rules.sorted = sort(rules, by="lift")
inspect(rules.sorted)
library("arulesViz", lib.loc="~/R/win-library/3.2")
plot(rules)
plot(rules, method="graph", control=list(type="items"))
rules <- apriori(myData_mat, parameter = list(minlen=2, supp=0.01, conf=0.8), appearance = list(rhs=c("Walc=5", "Walc=4"),default = "lhs"))
##inspect(rules)
rules.sorted = sort(rules, by="lift")
inspect(rules.sorted)
sink("output_mat1.txt")
rules <- apriori(myData_mat, parameter = list(minlen=2, supp=0.01, conf=0.8), appearance = list(rhs=c("Walc=5", "Walc=4"),default = "lhs"))
##inspect(rules)
rules.sorted = sort(rules, by="lift")
inspect(rules.sorted)
library("arulesViz", lib.loc="~/R/win-library/3.2")
plot(rules)
library("arulesViz", lib.loc="~/R/win-library/3.2")
plot(rules)
sink("output_mat1.txt")
rules1 <- apriori(myData_mat, parameter = list(minlen=2, supp=0.01, conf=0.8), appearance = list(rhs=c("Walc=5", "Walc=4"),default = "lhs"))
##inspect(rules)
rules1.sorted = sort(rules1, by="lift")
inspect(rules1.sorted)
library("arulesViz", lib.loc="~/R/win-library/3.2")
plot(rules1)
plot(rules1)
library("arulesViz", lib.loc="~/R/win-library/3.2")
plot(rules1.sorted)
plot(rules1)
student.mat <- read.csv("C:/student-mat.csv", sep=";")
View(student.mat)
myData_mat = student.mat
dim(myData_mat)
summary(myData_mat)
##set following variables as factor variables
myData_mat[,3]=as.ordered(myData_mat[,3])
myData_mat[,7]=as.ordered(myData_mat[,7])
myData_mat[,8]=as.ordered(myData_mat[,8])
myData_mat[,13]=as.ordered(myData_mat[,13])
myData_mat[,14]=as.ordered(myData_mat[,14])
myData_mat[,15]=as.ordered(myData_mat[,15])
myData_mat[,24]=as.ordered(myData_mat[,24])
myData_mat[,25]=as.ordered(myData_mat[,25])
myData_mat[,26]=as.ordered(myData_mat[,26])
myData_mat[,27]=as.ordered(myData_mat[,27])
myData_mat[,28]=as.ordered(myData_mat[,28])
myData_mat[,29]=as.ordered(myData_mat[,29])
myData_mat[,30]=as.ordered(myData_mat[,30])
myData_mat[,31]=as.ordered(myData_mat[,31])
myData_mat[,32]=as.ordered(myData_mat[,32])
myData_mat[,33]=as.ordered(myData_mat[,33])
## show summary after changing numerical to factor variables
summary(myData_mat)
sink("output_mat-a.txt")
library("arules", lib.loc="~/R/win-library/3.2")
##rules = apriori(myData_mat)
rules <- apriori(myData_mat, parameter = list(minlen=2, supp=0.01, conf=0.8), appearance = list(rhs=c("Dalc=5", "Dalc=4"),default = "lhs"))
##inspect(rules)
rules.sorted = sort(rules, by="lift")
inspect(rules.sorted)
library("arulesViz", lib.loc="~/R/win-library/3.2")
plot(rules)
